# Generated by Django 5.2.7 on 2025-11-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venue.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('venue', 'booking_date')},
        ),
    ]
