# Generated by Django 5.2.7 on 2025-10-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('venue', '0012_alter_venue_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='end_date',
            new_name='booking_date',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('venue', 'booking_date')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_date',
        ),
    ]
