# Generated by Django 5.2.7 on 2025-10-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('home_teams', models.TextField(blank=True)),
                ('capacity', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
