# Generated by Django 5.2.7 on 2025-10-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='venues/'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
