# Generated by Django 5.2.7 on 2025-10-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_venue_description_venue_thumbnail_alter_venue_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='venue',
            name='thumbnail',
            field=models.CharField(blank=True, default='img/default_venue.jpg', max_length=255),
        ),
    ]
