# Generated by Django 5.2.8 on 2025-12-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_alter_venue_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='facilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='rules',
            field=models.TextField(blank=True, default=''),
        ),
    ]
