# Generated by Django 5.2.7 on 2025-10-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_alter_venue_description_alter_venue_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='thumbnail',
            field=models.CharField(blank=True, default='https://via.placeholder.com/300x200', max_length=500),
        ),
    ]
