# Generated by Django 5.2.7 on 2025-10-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_alter_venue_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='thumbnail',
            field=models.TextField(blank=True, default='https://via.placeholder.com/300x200'),
        ),
    ]
