# Generated by Django 5.2.7 on 2025-10-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_alter_venue_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='thumbnail',
            field=models.CharField(blank=True, default='img/default_venue.jpg', max_length=255),
        ),
    ]
