# Generated by Django 5.2.6 on 2025-10-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_alter_venue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
