# Generated by Django 5.2.7 on 2025-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_venue_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
