# Generated by Django 5.2.7 on 2025-10-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0011_alter_venue_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
