# Generated by Django 5.2.7 on 2025-10-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0012_alter_venue_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='venue',
            name='thumbnail',
            field=models.TextField(blank=True, default='static/img/placeholder.png'),
        ),
    ]
