# Generated by Django 5.2.7 on 2025-10-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0013_alter_venue_rating_alter_venue_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='thumbnail',
            field=models.TextField(blank=True, default='img/placeholder.png'),
        ),
    ]
