# Generated by Django 5.2.6 on 2025-10-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0016_alter_venue_price_alter_venue_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='thumbnail',
            field=models.TextField(blank=True, default='../../static/img/placeholder.png'),
        ),
    ]
