# Generated by Django 5.2.7 on 2025-11-17 12:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0017_alter_venue_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
