# Generated by Django 5.2.7 on 2025-10-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
